title: Lista Nacional de Espécies Ameaçadas Sob a Perspectiva do Acesso e Processamento de Dados
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: true
github:
  csv_url: https://tawnunes.github.io/categoria-ameaca-BR/dados/processados/lista_especies_ameacadas_P148.csv
  xlsx_url: https://tawnunes.github.io/categoria-ameaca-BR/dados/processados/lista_especies_ameacadas_P148.xlsx